spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/selvasingh/spring-boot-end-to-end-tls-ssl-config.git
        native:
          search-locations: classpath:.
  profiles:
    active: native
